CREATE TABLE [dbo].[CHATS](
[ID]      INT           IDENTITY (1,1) NOT NULL,
[USER]       NVARCHAR (50) NULL,
[TEXT]      NVARCHAR (50) NULL,
[SENDTIME] DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
)