--INSERT INTO [MESSAGES] ([TEXT], [FROM], [TO]) VALUES('hi', 'Adam', 'Eve');
--INSERT INTO MESSAGES ([TEXT], [FROM], [TO]) VALUES('hwy', 'Eve', 'Adam');
--INSERT INTO MESSAGES ([TEXT], [FROM], [TO]) VALUES('how are you?','Adam', 'Eve');
--INSERT INTO MESSAGES ([TEXT], [FROM], [TO]) VALUES('im fine, u', 'Eve', 'Adam');
--INSERT INTO MESSAGES ([TEXT], [FROM], [TO]) VALUES('im good Thank you!', 'Adam', 'Eve');
--INSERT INTO MESSAGES ([TEXT], [FROM], [TO]) VALUES('yellow', 'Eve', 'Andrew');
--INSERT INTO MESSAGES ([TEXT], [FROM], [TO]) VALUES('sub bitch', 'Andrew', 'Eve');
--INSERT INTO MESSAGES ([TEXT], [FROM], [TO]) VALUES('who u callin a bitch', 'Eve', 'Andrew');
--INSERT INTO MESSAGES ([TEXT], [FROM], [TO]) VALUES('you BITCH', 'Andrew', 'Eve');


DELETE FROM [MESSAGES];
--	ALTER TABLE [MESSAGES] ALTER COLUMN [SENDTIME] DATETIME NOT NULL;




--SELECT DATEDIFF_BIG(ms, '1970-01-01 00:00:00', GETUTCDATE());

--CREATE TABLE [dbo].[MESSAGES] (
--    [ID]       INT           IDENTITY (1, 1) NOT NULL,
--    [TEXT]     NVARCHAR (50) NOT NULL DEFAULT '',
--    [SENDTIME] DATETIME    NOT NULL DEFAULT GETUTCDATE() ,
--    [FROM]     NVARCHAR (50) NOT NULL,
--    [TO]       NVARCHAR (50) NOT NULL,
--    PRIMARY KEY CLUSTERED ([ID] ASC)
--);


select TEXT from [MESSAGES];

--msg per hour
SELECT CONVERT(bigint, COUNT(*)) , DATEDIFF_BIG(hh, '1970-01-01 00:00:00', [SENDTIME]) 
FROM MESSAGES GROUP BY DATEDIFF_BIG(hh, '1970-01-01 00:00:00', [SENDTIME]);

-- WORDS BY HOUR
SELECT SUM([WPH].[WORDS]), [WPH].[HOUR]
FROM 
	(SELECT (SELECT COUNT(*) FROM STRING_SPLIT(MSG.[TEXT], ' ')) AS [WORDS], 
			DATEDIFF_BIG(hh, '1970-01-01 00:00:00', MSG.[SENDTIME]) AS [HOUR]
	FROM MESSAGES AS MSG) AS [WPH]
GROUP BY [WPH].[HOUR]
;

--avg letters for all
SELECT ISNULL(AVG(CAST(LEN(REPLACE([TEXT],' ','')) as float)),0) FROM [MESSAGES]
--avg letters for user
SELECT AVG(CAST(LEN(REPLACE([TEXT],' ','')) as float)) FROM [MESSAGES] WHERE [FROM]='Adam';

--AVG TIME BETWEEN MSGS


SELECT CONVERT(bigint, COUNT(*)) AS y, CONVERT(bigint, DATEDIFF_BIG(hh, '1970-01-01 00:00:00', [SENDTIME])) AS x FROM chattar.dbo.MESSAGES GROUP BY DATEDIFF_BIG(hh, '1970-01-01 00:00:00', [SENDTIME]);